void Histoplot()
{

  gROOT->SetBatch(1);
  gStyle->SetOptStat(0);

  // Write histos to root file
  TFile *file1 = TFile::Open("Histogram_Data.root");
  TFile *file2 = TFile::Open("Histogram_GJets.root");
  TFile *file3 = TFile::Open("Histogram_QCD.root");
  TH1* hist1_1 = (TH1*)file1->Get("1"); //p_pt
  TH1* hist1_2 = (TH1*)file1->Get("2"); //p_eta
  TH1* hist1_3 = (TH1*)file1->Get("3"); //j_pt
  TH1* hist1_4 = (TH1*)file1->Get("4"); //j_eta
  TH1* hist1_5 = (TH1*)file1->Get("5"); //j_e
  TH1* hist1_6 = (TH1*)file1->Get("6"); //j_mass
  TH1* hist1_7 = (TH1*)file1->Get("7"); //j_tau21
  TH1* hist1_8 = (TH1*)file1->Get("8"); //s_cos
  TH1* hist1_9 = (TH1*)file1->Get("9"); //s_ptm
  TH1* hist1_10 = (TH1*)file1->Get("10"); //s_invmass
  TH1* hist2_1 = (TH1*)file2->Get("1");
  TH1* hist2_2 = (TH1*)file2->Get("2");
  TH1* hist2_3 = (TH1*)file2->Get("3");
  TH1* hist2_4 = (TH1*)file2->Get("4");
  TH1* hist2_5 = (TH1*)file2->Get("5");
  TH1* hist2_6 = (TH1*)file2->Get("6");
  TH1* hist2_7 = (TH1*)file2->Get("7");
  TH1* hist2_8 = (TH1*)file2->Get("8");
  TH1* hist2_9 = (TH1*)file2->Get("9");
  TH1* hist2_10 = (TH1*)file2->Get("10");
  TH1* hist3_1 = (TH1*)file3->Get("1");
  TH1* hist3_2 = (TH1*)file3->Get("2");
  TH1* hist3_3 = (TH1*)file3->Get("3");
  TH1* hist3_4 = (TH1*)file3->Get("4");
  TH1* hist3_5 = (TH1*)file3->Get("5");
  TH1* hist3_6 = (TH1*)file3->Get("6");
  TH1* hist3_7 = (TH1*)file3->Get("7");
  TH1* hist3_8 = (TH1*)file3->Get("8");
  TH1* hist3_9 = (TH1*)file3->Get("9");
  TH1* hist3_10 = (TH1*)file3->Get("10");

  hist2_1->Scale(1.45);
  hist2_2->Scale(1.45);
  hist2_3->Scale(1.45);
  hist2_4->Scale(1.45);
  hist2_5->Scale(1.45);
  hist2_6->Scale(1.45);
  hist2_7->Scale(1.45);
  hist2_8->Scale(1.45);
  hist2_9->Scale(1.45);
  hist2_10->Scale(1.45);
  hist3_1->Scale(0.01);
  hist3_2->Scale(0.01);
  hist3_3->Scale(0.01);
  hist3_4->Scale(0.01);
  hist3_5->Scale(0.01);
  hist3_6->Scale(0.01);
  hist3_7->Scale(0.01);
  hist3_8->Scale(0.01);
  hist3_9->Scale(0.01);
  hist3_10->Scale(0.01);

  int color1 = 2;
  int color2 = 8;
  int color3 = 7;

  hist1_1->SetLineColor(1);
  hist1_2->SetLineColor(1);
  hist1_3->SetLineColor(1);
  hist1_4->SetLineColor(1);
  hist1_5->SetLineColor(1);
  hist1_6->SetLineColor(1);
  hist1_7->SetLineColor(1);
  hist1_8->SetLineColor(1);
  hist1_9->SetLineColor(1);
  hist1_10->SetLineColor(1);
  hist2_1->SetLineColor(1);
  hist2_2->SetLineColor(1);
  hist2_3->SetLineColor(1);
  hist2_4->SetLineColor(1);
  hist2_5->SetLineColor(1);
  hist2_6->SetLineColor(1);
  hist2_7->SetLineColor(1);
  hist2_8->SetLineColor(1);
  hist2_9->SetLineColor(1);
  hist2_10->SetLineColor(1);
  hist3_1->SetLineColor(1);
  hist3_2->SetLineColor(1);
  hist3_3->SetLineColor(1);
  hist3_4->SetLineColor(1);
  hist3_5->SetLineColor(1);
  hist3_6->SetLineColor(1);
  hist3_7->SetLineColor(1);
  hist3_8->SetLineColor(1);
  hist3_9->SetLineColor(1);
  hist3_10->SetLineColor(1);

  hist2_1->SetFillColor(color2);
  hist2_2->SetFillColor(color2);
  hist2_3->SetFillColor(color2);
  hist2_4->SetFillColor(color2);
  hist2_5->SetFillColor(color2);
  hist2_6->SetFillColor(color2);
  hist2_7->SetFillColor(color2);
  hist2_8->SetFillColor(color2);
  hist2_9->SetFillColor(color2);
  hist2_10->SetFillColor(color2);
  hist3_1->SetFillColor(color3);
  hist3_2->SetFillColor(color3);
  hist3_3->SetFillColor(color3);
  hist3_4->SetFillColor(color3);
  hist3_5->SetFillColor(color3);
  hist3_6->SetFillColor(color3);
  hist3_7->SetFillColor(color3);
  hist3_8->SetFillColor(color3);
  hist3_9->SetFillColor(color3);
  hist3_10->SetFillColor(color3);

  hist1_1->SetLineWidth(2);
  hist1_2->SetLineWidth(2);
  hist1_3->SetLineWidth(2);
  hist1_4->SetLineWidth(2);
  hist1_5->SetLineWidth(2);
  hist1_6->SetLineWidth(2);
  hist1_7->SetLineWidth(2);
  hist1_8->SetLineWidth(2);
  hist1_9->SetLineWidth(2);
  hist1_10->SetLineWidth(2);
  hist2_1->SetLineWidth(2);
  hist2_2->SetLineWidth(2);
  hist2_3->SetLineWidth(2);
  hist2_4->SetLineWidth(2);
  hist2_5->SetLineWidth(2);
  hist2_6->SetLineWidth(2);
  hist2_7->SetLineWidth(2);
  hist2_8->SetLineWidth(2);
  hist2_9->SetLineWidth(2);
  hist2_10->SetLineWidth(2);
  hist3_1->SetLineWidth(2);
  hist3_2->SetLineWidth(2);
  hist3_3->SetLineWidth(2);
  hist3_4->SetLineWidth(2);
  hist3_5->SetLineWidth(2);
  hist3_6->SetLineWidth(2);
  hist3_7->SetLineWidth(2);
  hist3_8->SetLineWidth(2);
  hist3_9->SetLineWidth(2);
  hist3_10->SetLineWidth(2);

  hist1_1->SetMarkerStyle(8);
  hist1_2->SetMarkerStyle(8);
  hist1_3->SetMarkerStyle(8);
  hist1_4->SetMarkerStyle(8);
  hist1_5->SetMarkerStyle(8);
  hist1_6->SetMarkerStyle(8);
  hist1_7->SetMarkerStyle(8);
  hist1_8->SetMarkerStyle(8);
  hist1_9->SetMarkerStyle(8);
  hist1_10->SetMarkerStyle(8);

  cout<<"OK";

  //Stacked plots

  THStack *stack1 = new THStack("stack1","pt_{p}");
  THStack *stack2 = new THStack("stack2","eta_{p}");
  THStack *stack3 = new THStack("stack3","pt_{j}");
  THStack *stack4 = new THStack("stack4","eta_{j}");
  THStack *stack5 = new THStack("stack5","e_{j}");
  THStack *stack6 = new THStack("stack6","Jet softdrop mass");
  THStack *stack7 = new THStack("stack7","Jet tau21");
  THStack *stack8 = new THStack("stack8","cos(#theta*)");
  THStack *stack9 = new THStack("stack9","pt_{j} / M");
  THStack *stack10 = new THStack("stack10","Invariant mass");
  stack1->Add(hist3_1); stack1->Add(hist2_1);
  stack2->Add(hist3_2); stack2->Add(hist2_2);
  stack3->Add(hist3_3); stack3->Add(hist2_3);
  stack4->Add(hist3_4); stack4->Add(hist2_4);
  stack5->Add(hist3_5); stack5->Add(hist2_5);
  stack6->Add(hist3_6); stack6->Add(hist2_6);
  stack7->Add(hist3_7); stack7->Add(hist2_7);
  stack8->Add(hist3_8); stack8->Add(hist2_8);
  stack9->Add(hist3_9); stack9->Add(hist2_9);
  stack10->Add(hist3_10); stack10->Add(hist2_10);

  TLegend *legend = new TLegend(0.65,0.8,0.9,0.9);

  TCanvas *c01 = new TCanvas("c01","pt_{#gamma}",1200,900);
  TAxis *xaxis = hist1_1->GetXaxis();
  TAxis *yaxis = hist1_1->GetYaxis();
  xaxis->SetTitle("pt_{#gamma} (GeV)");
  yaxis->SetTitle("Entries");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  c01->SetLogy();
  c01->cd();
  hist1_1->Draw("E");
  stack1->Draw("SAMEHIST");
  hist1_1->Draw("ESAME");
  hist1_1->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_1,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_1,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_1,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c01->Print("p_pt.png");

  TCanvas *c02 = new TCanvas("c02","eta_{#gamma}",1200,900);
  xaxis = hist1_2->GetXaxis();
  yaxis = hist1_2->GetYaxis();
  xaxis->SetTitle("eta_{#gamma}");
  yaxis->SetTitle("Entries");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  c02->SetLogy();
  c02->cd();
  hist1_2->Draw("E");
  stack2->Draw("SAMEHIST");
  hist1_2->Draw("ESAME");
  hist1_2->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_2,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_2,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_2,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c02->Print("p_eta.png");

  TCanvas *c03 = new TCanvas("c03","pt AK8Jet",1200,900);
  xaxis = hist1_3->GetXaxis();
  yaxis = hist1_3->GetYaxis();
  xaxis->SetTitle("pt AK8Jet (GeV)");
  yaxis->SetTitle("Entries");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  //yaxis->SetRangeUser(0,2000);
  c03->SetLogy();
  c03->cd();
  hist1_3->Draw("E");
  stack3->Draw("SAMEHIST");
  hist1_3->Draw("ESAME");
  hist1_3->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_3,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_3,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_3,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c03->Print("j_pt.png");

  TCanvas *c04 = new TCanvas("c04","eta AK8Jet",1200,900);
  xaxis = hist1_4->GetXaxis();
  yaxis = hist1_4->GetYaxis();
  xaxis->SetTitle("eta AK8Jet");
  yaxis->SetTitle("Entries");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  c04->SetLogy();
  c04->cd();
  hist1_4->Draw("E");
  stack4->Draw("SAMEHIST");
  hist1_4->Draw("ESAME");
  hist1_4->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_4,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_4,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_4,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c04->Print("j_eta.png");

  TCanvas *c05 = new TCanvas("c05","E AK8Jet",1200,900);
  xaxis = hist1_5->GetXaxis();
  yaxis = hist1_5->GetYaxis();
  xaxis->SetTitle("E AK8Jet (GeV)");
  yaxis->SetTitle("Entries");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  c05->SetLogy();
  c05->cd();
  hist1_5->Draw("E");
  stack5->Draw("SAMEHIST");
  hist1_5->Draw("ESAME");
  hist1_5->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_5,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_5,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_5,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c05->Print("j_e.png");

  TCanvas *c06 = new TCanvas("c06","mass softdrop AK8Jet",1200,900);
  xaxis = hist1_6->GetXaxis();
  yaxis = hist1_6->GetYaxis();
  xaxis->SetTitle("mass softdrop AK8Jet (GeV)");
  yaxis->SetTitle("a.u.");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  //yaxis->SetRangeUser(0,400);
  c06->SetLogy();
  c06->cd();
  hist1_6->Draw("E");
  stack6->Draw("SAMEHIST");
  hist1_6->Draw("ESAME");
  hist1_6->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_6,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_6,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_6,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c06->Print("j_masssd.png");

  TCanvas *c07 = new TCanvas("c07","tau21 AK8Jet",1200,900);
  xaxis = hist1_7->GetXaxis();
  yaxis = hist1_7->GetYaxis();
  xaxis->SetTitle("tau21 AK8Jet");
  yaxis->SetTitle("Entries");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  c07->SetLogy();
  c07->cd();
  hist1_7->Draw("E");
  stack7->Draw("SAMEHIST");
  hist1_7->Draw("ESAME");
  hist1_7->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_7,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_7,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_7,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c07->Print("j_tau21.png");

  TCanvas *c08 = new TCanvas("c8","cos AK8Jet",1200,900);
  xaxis = hist1_8->GetXaxis();
  yaxis = hist1_8->GetYaxis();
  xaxis->SetTitle("cos(#theta*)");
  yaxis->SetTitle("Entries");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  c08->SetLogy();
  c08->cd();
  hist1_8->Draw("E");
  stack8->Draw("SAMEHIST");
  hist1_8->Draw("ESAME");
  hist1_8->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_8,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_8,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_8,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c08->Print("s_cos.png");

  TCanvas *c09 = new TCanvas("c9","ptm AK8Jet",1200,900);
  xaxis = hist1_9->GetXaxis();
  yaxis = hist1_9->GetYaxis();
  xaxis->SetTitle("pt/M");
  yaxis->SetTitle("Entries");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  c09->SetLogy();
  c09->cd();
  hist1_9->Draw("E");
  stack9->Draw("SAMEHIST");
  hist1_9->Draw("ESAME");
  hist1_9->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_9,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_9,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_9,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c09->Print("s_ptm.png");

  TCanvas *c10 = new TCanvas("c10","invmass",1200,900);
  xaxis = hist1_10->GetXaxis();
  yaxis = hist1_10->GetYaxis();
  xaxis->SetTitle("Invariant mass (GeV)");
  yaxis->SetTitle("Entries");
  yaxis->SetTitleOffset(1.3);
  yaxis->SetRangeUser(0.01,10000000);
  c10->SetLogy();
  c10->cd();
  hist1_10->Draw("E");
  stack10->Draw("SAMEHIST");
  hist1_10->Draw("ESAME");
  hist1_10->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist1_10,"2017 Data, SinglePhoton","lep");
  legend->AddEntry(hist2_10,"2017 MC, GJets(w. k factor)","f");
  legend->AddEntry(hist3_10,"2017 MC, QCD(w. k factor)","f");
  legend->Draw();
  c10->Print("s_invmass.png");

  // Residual plot
  TH1 *data = NULL;
  TH1 *bkg = NULL;

  data = (TH1*)hist1_1->Clone();
  bkg = hist2_1; bkg->Add(hist3_1);
  hist1_1->Add(bkg,-1);
  hist1_1->Divide(data);
  TCanvas *r1_1 = new TCanvas("r1_1","r1_1",1200,300);
  r1_1->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_1->GetXaxis();
  yaxis = hist1_1->GetYaxis();
  xaxis->SetTitle("pt_{p}");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetNdivisions(5);
  yaxis->SetTitleSize(0.08);
  r1_1->SetBottomMargin(0.18);
  r1_1->SetTopMargin(0.18);
  r1_1->SetGrid();
  hist1_1->Draw("PE1");
  r1_1->Update();
  r1_1->Print("ppt_res.png");

  data = (TH1*)hist1_2->Clone();
  bkg = hist2_2; bkg->Add(hist3_2);
  hist1_2->Add(bkg,-1);
  hist1_2->Divide(data);
  TCanvas *r1_2 = new TCanvas("r1_2","r1_2",1200,300);
  r1_2->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_2->GetXaxis();
  yaxis = hist1_2->GetYaxis();
  xaxis->SetTitle("eta_{p}");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetTitleSize(0.08);
  yaxis->SetNdivisions(5);
  r1_2->SetBottomMargin(0.18);
  r1_2->SetTopMargin(0.18);
  r1_2->SetGrid();
  hist1_2->Draw("PE1");
  r1_2->Update();
  r1_2->Print("peta_res.png");

  data = (TH1*)hist1_3->Clone();
  bkg = hist2_3; bkg->Add(hist3_3);
  hist1_3->Add(bkg,-1);
  hist1_3->Divide(data);
  TCanvas *r1_3 = new TCanvas("r1_3","r1_3",1200,300);
  r1_3->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_3->GetXaxis();
  yaxis = hist1_3->GetYaxis();
  xaxis->SetTitle("pt_{j}");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetTitleSize(0.08);
  yaxis->SetNdivisions(5);
  r1_3->SetBottomMargin(0.18);
  r1_3->SetTopMargin(0.18);
  r1_3->SetGrid();
  hist1_3->Draw("PE1");
  r1_3->Update();
  r1_3->Print("jpt_res.png");

  data = (TH1*)hist1_4->Clone();
  bkg = hist2_4; bkg->Add(hist3_4);
  hist1_4->Add(bkg,-1);
  hist1_4->Divide(data);
  TCanvas *r1_4 = new TCanvas("r1_4","r1_4",1200,300);
  r1_4->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_4->GetXaxis();
  yaxis = hist1_4->GetYaxis();
  xaxis->SetTitle("eta_{j}");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetTitleSize(0.08);
  yaxis->SetNdivisions(5);
  r1_4->SetBottomMargin(0.18);
  r1_4->SetTopMargin(0.18);
  r1_4->SetGrid();
  hist1_4->Draw("PE1");
  r1_4->Update();
  r1_4->Print("jeta_res.png");

  data = (TH1*)hist1_5->Clone();
  bkg = hist2_5; bkg->Add(hist3_5);
  hist1_5->Add(bkg,-1);
  hist1_5->Divide(data);
  TCanvas *r1_5 = new TCanvas("r1_5","r1_5",1200,300);
  r1_5->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_5->GetXaxis();
  yaxis = hist1_5->GetYaxis();
  xaxis->SetTitle("E_{j}");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetTitleSize(0.08);
  yaxis->SetNdivisions(5);
  r1_5->SetBottomMargin(0.18);
  r1_5->SetTopMargin(0.18);
  r1_5->SetGrid();
  hist1_5->Draw("PE1");
  r1_5->Update();
  r1_5->Print("je_res.png");

  data = (TH1*)hist1_6->Clone();
  bkg = hist2_6; bkg->Add(hist3_6);
  hist1_6->Add(bkg,-1);
  hist1_6->Divide(data);
  TCanvas *r1_6 = new TCanvas("r1_6","r1_6",1200,300);
  r1_6->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_6->GetXaxis();
  yaxis = hist1_6->GetYaxis();
  xaxis->SetTitle("mass_{j}");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetTitleSize(0.08);
  yaxis->SetNdivisions(5);
  r1_6->SetBottomMargin(0.18);
  r1_6->SetTopMargin(0.18);
  r1_6->SetGrid();
  hist1_6->Draw("PE1");
  r1_6->Update();
  r1_6->Print("jmass_res.png");

  data = (TH1*)hist1_7->Clone();
  bkg = hist2_7; bkg->Add(hist3_7);
  hist1_7->Add(bkg,-1);
  hist1_7->Divide(data);
  TCanvas *r1_7 = new TCanvas("r1_7","r1_7",1200,300);
  r1_7->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_7->GetXaxis();
  yaxis = hist1_7->GetYaxis();
  xaxis->SetTitle("tau21");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetTitleSize(0.08);
  yaxis->SetNdivisions(5);
  r1_7->SetBottomMargin(0.18);
  r1_7->SetTopMargin(0.18);
  r1_7->SetGrid();
  hist1_7->Draw("PE1");
  r1_7->Update();
  r1_7->Print("jtau21_res.png");

  data = (TH1*)hist1_8->Clone();
  bkg = hist2_8; bkg->Add(hist3_8);
  hist1_8->Add(bkg,-1);
  hist1_8->Divide(data);
  TCanvas *r1_8 = new TCanvas("r1_8","r1_8",1200,300);
  r1_8->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_8->GetXaxis();
  yaxis = hist1_8->GetYaxis();
  xaxis->SetTitle("cos(#theta*)");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetTitleSize(0.08);
  yaxis->SetNdivisions(5);
  r1_8->SetBottomMargin(0.18);
  r1_8->SetTopMargin(0.18);
  r1_8->SetGrid();
  hist1_8->Draw("PE1");
  r1_8->Update();
  r1_8->Print("scos_res.png");

  data = (TH1*)hist1_9->Clone();
  bkg = hist2_9; bkg->Add(hist3_9);
  hist1_9->Add(bkg,-1);
  hist1_9->Divide(data);
  TCanvas *r1_9 = new TCanvas("r1_9","r1_9",1200,300);
  r1_9->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_9->GetXaxis();
  yaxis = hist1_9->GetYaxis();
  xaxis->SetTitle("pt_{j}/M");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetTitleSize(0.08);
  yaxis->SetNdivisions(5);
  r1_9->SetBottomMargin(0.18);
  r1_9->SetTopMargin(0.18);
  r1_9->SetGrid();
  hist1_9->Draw("PE1");
  r1_9->Update();
  r1_9->Print("sptm_res.png");

  data = (TH1*)hist1_10->Clone();
  bkg = hist2_10; bkg->Add(hist3_10);
  hist1_10->Add(bkg,-1);
  hist1_10->Divide(data);
  TCanvas *r1_10 = new TCanvas("r1_10","r1_10",1200,300);
  r1_10->cd();
  bkg->SetMarkerStyle(8);
  xaxis = hist1_10->GetXaxis();
  yaxis = hist1_10->GetYaxis();
  xaxis->SetTitle("M_{j#gamma}");
  yaxis->SetTitle("#frac{DATA-MC}{DATA}");
  yaxis->SetTitleOffset(0.5);
  yaxis->SetRangeUser(-1,1);
  xaxis->SetLabelSize(0.08);
  xaxis->SetTitleSize(0.08);
  yaxis->SetLabelSize(0.08);
  yaxis->SetTitleSize(0.08);
  yaxis->SetNdivisions(5);
  r1_10->SetBottomMargin(0.18);
  r1_10->SetTopMargin(0.18);
  r1_10->SetGrid();
  hist1_10->Draw("PE1");
  r1_10->Update();
  r1_10->Print("sinvmass_res.png");
}
