//MC selection
#if !defined(__CINT__) || defined(__MAKECINT__)
#include <TROOT.h>                  // access to gROOT, entry point to ROOT system
#include <TSystem.h>                // interface to OS
#include <TFile.h>                  // file handle class
#include <TTree.h>                  // class to access ntuples
#include <TClonesArray.h>           // ROOT array class
#include <TBenchmark.h>             // class to track macro running statistics
#include <TVector2.h>               // 2D vector class
#include <TMath.h>                  // ROOT math library
#include <vector>                   // STL vector class
#include <iostream>                 // standard I/O
#include <iomanip>                  // functions to format standard I/O
#include <fstream>                  // functions for file I/O
#include "TLorentzVector.h"         // 4-vector class
#include <THStack.h>
#include <TStyle.h>
#include <TCanvas.h>
#include <TGraph.h>
#include <TLegend.h>
#include <TF1.h>
#include <TEfficiency.h>
#include "TGraphAsymmErrors.h"
#include "TH1D.h"
#include "TRandom.h"
#include <algorithm>
#include <map>
#include "/afs/cern.ch/work/x/xuyan/work5/PROD17/AN/AN-19-280/utils/general/tdrstyle.C"
#include "/afs/cern.ch/work/x/xuyan/work5/PROD17/AN/AN-19-280/utils/general/CMS_lumi.C"
#endif

void MCvalidation()
{
  gROOT->SetBatch(1);
  lumi_13TeV = "137.19 fb^{-1}";
  writeExtraText = 1;
  lumiTextOffset = 0.15;
  bool plot_CMS = true;
  extraText = "";
  lumiTextSize = 0.3;
  cmsTextSize = 0.45;
  int iPeriod = 12;
  int iPos = 0;
  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);
  gStyle->SetTitleSize(0.04,"XYZ");
  gStyle->SetLabelSize(0.04,"XYZ");
  gStyle->SetFrameLineWidth(2);
  gStyle->SetLegendTextSize(0.02);
  gStyle->SetBarWidth(2);
  gStyle->SetHistLineWidth(2);

  TH1 *hist11 = new TH1F("11","pt_{#gamma}",100,0,3000);
  TH1 *hist12 = new TH1F("12","eta_{#gamma}",50,-2,2);
  TH1 *hist13 = new TH1F("13","pt_{j}",100,0,3000);
  TH1 *hist14 = new TH1F("14","eta_{j}",50,-2,2);
  TH1 *hist15 = new TH1F("15","E_{j}",100,0,3000);
  TH1 *hist16 = new TH1F("16","masssoftdrop_{j}",80,30,110);
  TH1 *hist17 = new TH1F("17","tau21_{j}",50,0,1);
  TH1 *hist18 = new TH1F("18","cos(#theta*)_{p}",50,0,1);
  TH1 *hist19 = new TH1F("19","pt/M",50,0,2);
  TH1 *hist110 = new TH1F("110","invariant mass",100,0,4000);
  TH1 *hist111 = new TH1F("111","seperation",50,0,8);
  TH1 *hist21 = new TH1F("21","pt_{#gamma}",100,0,3000);
  TH1 *hist22 = new TH1F("22","eta_{#gamma}",50,-2,2);
  TH1 *hist23 = new TH1F("23","pt_{j}",100,0,3000);
  TH1 *hist24 = new TH1F("24","eta_{j}",50,-2,2);
  TH1 *hist25 = new TH1F("25","E_{j}",100,0,3000);
  TH1 *hist26 = new TH1F("26","masssoftdrop_{j}",80,30,110);
  TH1 *hist27 = new TH1F("27","tau21_{j}",50,0,1);
  TH1 *hist28 = new TH1F("28","cos(#theta*)_{p}",50,0,1);
  TH1 *hist29 = new TH1F("29","pt/M",50,0,2);
  TH1 *hist210 = new TH1F("210","invariant mass",100,0,4000);
  TH1 *hist211 = new TH1F("211","seperation",50,0,8);
  TH1 *hist31 = new TH1F("31","pt_{#gamma}",100,0,3000);
  TH1 *hist32 = new TH1F("32","eta_{#gamma}",50,-2,2);
  TH1 *hist33 = new TH1F("33","pt_{j}",100,0,3000);
  TH1 *hist34 = new TH1F("34","eta_{j}",50,-2,2);
  TH1 *hist35 = new TH1F("35","E_{j}",100,0,3000);
  TH1 *hist36 = new TH1F("36","masssoftdrop_{j}",80,30,110);
  TH1 *hist37 = new TH1F("37","tau21_{j}",50,0,1);
  TH1 *hist38 = new TH1F("38","cos(#theta*)_{p}",50,0,1);
  TH1 *hist39 = new TH1F("39","pt/M",50,0,2);
  TH1 *hist310 = new TH1F("310","invariant mass",100,0,4000);
  TH1 *hist311 = new TH1F("311","seperation",50,0,8);
  TH1 *hist3a1 = new TH1F("3a1","pt_{#gamma}",100,0,3000);
  TH1 *hist3a2 = new TH1F("3a2","eta_{#gamma}",50,-2,2);
  TH1 *hist3a3 = new TH1F("3a3","pt_{j}",100,0,3000);
  TH1 *hist3a4 = new TH1F("3a4","eta_{j}",50,-2,2);
  TH1 *hist3a5 = new TH1F("3a5","E_{j}",100,0,3000);
  TH1 *hist3a6 = new TH1F("3a6","masssoftdrop_{j}",80,30,110);
  TH1 *hist3a7 = new TH1F("3a7","tau21_{j}",50,0,1);
  TH1 *hist3a8 = new TH1F("3a8","cos(#theta*)_{p}",50,0,1);
  TH1 *hist3a9 = new TH1F("3a9","pt/M",50,0,2);
  TH1 *hist3a10 = new TH1F("3a10","invariant mass",100,0,4000);
  TH1 *hist3a11 = new TH1F("3a11","seperation",50,0,8);
  TH1 *hist41 = new TH1F("41","pt_{#gamma}",100,0,3000);
  TH1 *hist42 = new TH1F("42","eta_{#gamma}",50,-2,2);
  TH1 *hist43 = new TH1F("43","pt_{j}",100,0,3000);
  TH1 *hist44 = new TH1F("44","eta_{j}",50,-2,2);
  TH1 *hist45 = new TH1F("45","E_{j}",100,0,3000);
  TH1 *hist46 = new TH1F("46","masssoftdrop_{j}",80,30,110);
  TH1 *hist47 = new TH1F("47","tau21_{j}",50,0,1);
  TH1 *hist48 = new TH1F("48","cos(#theta*)_{p}",50,0,1);
  TH1 *hist49 = new TH1F("49","pt/M",50,0,2);
  TH1 *hist410 = new TH1F("410","invariant mass",100,0,4000);
  TH1 *hist411 = new TH1F("411","seperation",50,0,8);
  TH1 *hist51 = new TH1F("51","pt_{#gamma}",100,0,3000);
  TH1 *hist52 = new TH1F("52","eta_{#gamma}",50,-2,2);
  TH1 *hist53 = new TH1F("53","pt_{j}",100,0,3000);
  TH1 *hist54 = new TH1F("54","eta_{j}",50,-2,2);
  TH1 *hist55 = new TH1F("55","E_{j}",100,0,3000);
  TH1 *hist56 = new TH1F("56","masssoftdrop_{j}",80,30,110);
  TH1 *hist57 = new TH1F("57","tau21_{j}",50,0,1);
  TH1 *hist58 = new TH1F("58","cos(#theta*)_{p}",50,0,1);
  TH1 *hist59 = new TH1F("59","pt/M",50,0,2);
  TH1 *hist510 = new TH1F("510","invariant mass",100,0,4000);
  TH1 *hist511 = new TH1F("511","seperation",50,0,8);
  TH1 *hist61 = new TH1F("61","pt_{#gamma}",100,0,3000);
  TH1 *hist62 = new TH1F("62","eta_{#gamma}",50,-2,2);
  TH1 *hist63 = new TH1F("63","pt_{j}",100,0,3000);
  TH1 *hist64 = new TH1F("64","eta_{j}",50,-2,2);
  TH1 *hist65 = new TH1F("65","E_{j}",100,0,3000);
  TH1 *hist66 = new TH1F("66","masssoftdrop_{j}",80,30,110);
  TH1 *hist67 = new TH1F("67","tau21_{j}",50,0,1);
  TH1 *hist68 = new TH1F("68","cos(#theta*)_{p}",50,0,1);
  TH1 *hist69 = new TH1F("69","pt/M",50,0,2);
  TH1 *hist610 = new TH1F("610","invariant mass",100,0,4000);
  TH1 *hist611 = new TH1F("611","seperation",50,0,8);
  TH1 *hist71 = new TH1F("71","pt_{#gamma}",100,0,3000);
  TH1 *hist72 = new TH1F("72","eta_{#gamma}",50,-2,2);
  TH1 *hist73 = new TH1F("73","pt_{j}",100,0,3000);
  TH1 *hist74 = new TH1F("74","eta_{j}",50,-2,2);
  TH1 *hist75 = new TH1F("75","E_{j}",100,0,3000);
  TH1 *hist76 = new TH1F("76","masssoftdrop_{j}",80,30,110);
  TH1 *hist77 = new TH1F("77","tau21_{j}",50,0,1);
  TH1 *hist78 = new TH1F("78","cos(#theta*)_{p}",50,0,1);
  TH1 *hist79 = new TH1F("79","pt/M",50,0,2);
  TH1 *hist710 = new TH1F("710","invariant mass",100,0,4000);
  TH1 *hist711 = new TH1F("711","seperation",50,0,8);
  // Local variables to store to outfile
  // Photon
  float photon_pt, photon_eta, photon_phi, photon_e, photon_mvaval, photon_mvacat;
  // Jet
  float ak8puppijet_pt, ak8puppijet_eta, ak8puppijet_phi, ak8puppijet_e, ak8puppijet_masssoftdropcorr, ak8puppijet_tau21;
  // System
  float sys_costhetastar, sys_ptoverm, m;
  
  // Open input file
  Float_t p_pt, p_eta, p_phi, p_e, p_mva, j_pt, j_eta, j_phi, j_e, j_mass, j_tau21, s_cos, s_ptm, s_mass, x_weight, x_kfactor;
  
  TFile *input = TFile::Open("/afs/cern.ch/work/x/xuyan/work5/PROD17/DATA/Run2/GJets_postproc_WGamma17_full_full_kfactor_jmcorr_May22.root");
  TTree* theTree = (TTree*)input->Get("Events");
  // Improt variables for cutting
  theTree->SetBranchAddress("photon_pt", &p_pt);
  theTree->SetBranchAddress("photon_eta", &p_eta);
  theTree->SetBranchAddress("photon_phi", &p_phi);
  theTree->SetBranchAddress("photon_e", &p_e);
  theTree->SetBranchAddress("photon_mvaval", &p_mva);
  theTree->SetBranchAddress("ak8puppijet_pt", &j_pt);
  theTree->SetBranchAddress("ak8puppijet_eta", &j_eta);
  theTree->SetBranchAddress("ak8puppijet_phi", &j_phi);
  theTree->SetBranchAddress("ak8puppijet_e", &j_e);
  theTree->SetBranchAddress("ak8puppijet_masssoftdropcorr", &j_mass);
  theTree->SetBranchAddress("ak8puppijet_tau21", &j_tau21);
  theTree->SetBranchAddress("sys_costhetastar", &s_cos);
  theTree->SetBranchAddress("sys_ptoverm", &s_ptm);
  theTree->SetBranchAddress("m", &s_mass);
  theTree->SetBranchAddress("xsec_weight", &x_weight);
  theTree->SetBranchAddress("xsec_kfactor", &x_kfactor);
  
  for (int ievt = 0; ievt<theTree->GetEntries();ievt++) {
    theTree->GetEntry(ievt);
	//if(p_pt < 225) continue;
	//if(j_pt < 225) continue;
    if((j_mass > 68 && j_mass < 94)){
	// if((j_mass > 68 && j_mass < 94) || (j_mass > 40 && j_mass < 65)){
	//x_kfactor = 1.21;
    hist11->Fill(p_pt, x_weight * x_kfactor * 3.30339);
    hist12->Fill(p_eta, x_weight * x_kfactor * 3.30339);
    hist13->Fill(j_pt, x_weight * x_kfactor * 3.30339);
    hist14->Fill(j_eta, x_weight * x_kfactor * 3.30339);
    hist15->Fill(j_e, x_weight * x_kfactor * 3.30339);
    hist16->Fill(j_mass, x_weight * x_kfactor * 3.30339);
    hist17->Fill(j_tau21, x_weight * x_kfactor * 3.30339);
    hist18->Fill(s_cos, x_weight * x_kfactor * 3.30339);
    hist19->Fill(s_ptm, x_weight * x_kfactor * 3.30339);
    hist110->Fill(s_mass, x_weight * x_kfactor * 3.30339);
    hist111->Fill(p_mva, x_weight * x_kfactor * 3.30339);  
	}
  }

  input = TFile::Open("/afs/cern.ch/work/x/xuyan/work5/PROD17/DATA/Run2/QCD_postproc_WGamma17_full_full_kfactor_jmcorr_May22.root");
  theTree = (TTree*)input->Get("Events");
  // Improt variables for cutting
  theTree->SetBranchAddress("photon_pt", &p_pt);
  theTree->SetBranchAddress("photon_eta", &p_eta);
  theTree->SetBranchAddress("photon_phi", &p_phi);
  theTree->SetBranchAddress("photon_e", &p_e);
  theTree->SetBranchAddress("photon_mvaval", &p_mva);
  theTree->SetBranchAddress("ak8puppijet_pt", &j_pt);
  theTree->SetBranchAddress("ak8puppijet_eta", &j_eta);
  theTree->SetBranchAddress("ak8puppijet_phi", &j_phi);
  theTree->SetBranchAddress("ak8puppijet_e", &j_e);
  theTree->SetBranchAddress("ak8puppijet_masssoftdropcorr", &j_mass);
  theTree->SetBranchAddress("ak8puppijet_tau21", &j_tau21);
  theTree->SetBranchAddress("sys_costhetastar", &s_cos);
  theTree->SetBranchAddress("sys_ptoverm", &s_ptm);
  theTree->SetBranchAddress("m", &s_mass);
  theTree->SetBranchAddress("xsec_weight", &x_weight);
  theTree->SetBranchAddress("xsec_kfactor", &x_kfactor);
  
  for (int ievt = 0; ievt<theTree->GetEntries();ievt++) {
    theTree->GetEntry(ievt);
	//if(p_pt < 225) continue;
	//if(j_pt < 225) continue;
	//x_kfactor = 1.03;
     if((j_mass > 68 && j_mass < 94)){
	// if((j_mass > 68 && j_mass < 94) || (j_mass > 40 && j_mass < 65)){
    hist21->Fill(p_pt, x_weight * x_kfactor * 3.30339);
    hist22->Fill(p_eta, x_weight * x_kfactor * 3.30339);
    hist23->Fill(j_pt, x_weight * x_kfactor * 3.30339);
    hist24->Fill(j_eta, x_weight * x_kfactor * 3.30339);
    hist25->Fill(j_e, x_weight * x_kfactor * 3.30339);
    hist26->Fill(j_mass, x_weight * x_kfactor * 3.30339);
    hist27->Fill(j_tau21, x_weight * x_kfactor * 3.30339);
    hist28->Fill(s_cos, x_weight * x_kfactor * 3.30339);
    hist29->Fill(s_ptm, x_weight * x_kfactor * 3.30339);
    hist210->Fill(s_mass, x_weight * x_kfactor * 3.30339);
    hist211->Fill(p_mva, x_weight * x_kfactor * 3.30339);  
	}
  }

  int SB = 0;
  int WB = 0;
  input = TFile::Open("/afs/cern.ch/work/x/xuyan/work5/PROD17/DATA/Run2/Run2Data_postproc_WGammaRun2_full_full_jmcorr_May22.root");
  theTree = (TTree*)input->Get("Events");
  // Improt variables for cutting
  theTree->SetBranchAddress("photon_pt", &p_pt);
  theTree->SetBranchAddress("photon_eta", &p_eta);
  theTree->SetBranchAddress("photon_phi", &p_phi);
  theTree->SetBranchAddress("photon_e", &p_e);
  theTree->SetBranchAddress("photon_mvaval", &p_mva);
  theTree->SetBranchAddress("ak8puppijet_pt", &j_pt);
  theTree->SetBranchAddress("ak8puppijet_eta", &j_eta);
  theTree->SetBranchAddress("ak8puppijet_phi", &j_phi);
  theTree->SetBranchAddress("ak8puppijet_e", &j_e);
  theTree->SetBranchAddress("ak8puppijet_masssoftdropcorr", &j_mass);
  theTree->SetBranchAddress("ak8puppijet_tau21", &j_tau21);
  theTree->SetBranchAddress("sys_costhetastar", &s_cos);
  theTree->SetBranchAddress("sys_ptoverm", &s_ptm);
  theTree->SetBranchAddress("m", &s_mass);
  //theTree->SetBranchAddress("xsec_weight", &x_weight);
  for (int ievt = 0; ievt<theTree->GetEntries();ievt++) {
    theTree->GetEntry(ievt);
	//if(p_pt < 225) continue;
	//if(j_pt < 225) continue;
    if(j_mass > 40 && j_mass < 65) {
		SB++;
		hist31->Fill(p_pt, 1);
		hist32->Fill(p_eta, 1);
		hist33->Fill(j_pt, 1);
		hist34->Fill(j_eta, 1);
		hist35->Fill(j_e, 1);
		hist36->Fill(j_mass, 1);
		hist37->Fill(j_tau21, 1);
		hist38->Fill(s_cos, 1);
		hist39->Fill(s_ptm, 1);
		hist310->Fill(s_mass, 1);
		hist311->Fill(p_mva, 1);  
		
		// hist31->Fill(p_pt, 1);
		// hist32->Fill(p_eta, 1);
		// hist33->Fill(j_pt, 1);
		// hist34->Fill(j_eta, 1);
		// hist35->Fill(j_e, 1);
		// hist36->Fill(j_mass, 1);
		// hist37->Fill(j_tau21, 1);
		// hist38->Fill(s_cos, 1);
		// hist39->Fill(s_ptm, 1);
		// hist310->Fill(s_mass, 1);
		// hist311->Fill(p_mva, 1);  
	}
	if(j_mass > 68 && j_mass < 94) {
		WB++;
		hist3a1->Fill(p_pt);
		hist3a2->Fill(p_eta);
		hist3a3->Fill(j_pt);
		hist3a4->Fill(j_eta);
		hist3a5->Fill(j_e);
		hist3a6->Fill(j_mass);
		hist3a7->Fill(j_tau21);
		hist3a8->Fill(s_cos);
		hist3a9->Fill(s_ptm);
		hist3a10->Fill(s_mass);
		hist3a11->Fill(p_mva); 
	}
  }
  

  input = TFile::Open("/afs/cern.ch/work/x/xuyan/work5/PROD17/DATA/2017/presel/SignalMC1000N_postproc_WGamma17_full_full_jmcorr_May22.root");
  theTree = (TTree*)input->Get("Events");
  // Improt variables for cutting
  theTree->SetBranchAddress("photon_pt", &p_pt);
  theTree->SetBranchAddress("photon_eta", &p_eta);
  theTree->SetBranchAddress("photon_phi", &p_phi);
  theTree->SetBranchAddress("photon_e", &p_e);
  theTree->SetBranchAddress("photon_mvaval", &p_mva);
  theTree->SetBranchAddress("ak8puppijet_pt", &j_pt);
  theTree->SetBranchAddress("ak8puppijet_eta", &j_eta);
  theTree->SetBranchAddress("ak8puppijet_phi", &j_phi);
  theTree->SetBranchAddress("ak8puppijet_e", &j_e);
  theTree->SetBranchAddress("ak8puppijet_masssoftdropcorr", &j_mass);
  theTree->SetBranchAddress("ak8puppijet_tau21", &j_tau21);
  theTree->SetBranchAddress("sys_costhetastar", &s_cos);
  theTree->SetBranchAddress("sys_ptoverm", &s_ptm);
  theTree->SetBranchAddress("m", &s_mass);
  //theTree->SetBranchAddress("xsec_weight", &x_weight);
  
  for (int ievt = 0; ievt<theTree->GetEntries();ievt++) {
    theTree->GetEntry(ievt);
    if(p_pt < 225) continue;
	if(j_pt < 225) continue;
    hist41->Fill(p_pt, 6.8595);
    hist42->Fill(p_eta, 6.8595);
    hist43->Fill(j_pt, 6.8595);
    hist44->Fill(j_eta, 6.8595);
    hist45->Fill(j_e, 6.8595);
    hist46->Fill(j_mass, 5*6.8595);
    hist47->Fill(j_tau21, 6.8595);
    hist48->Fill(s_cos, 6.8595);
    hist49->Fill(s_ptm, 6.8595);
    hist410->Fill(s_mass, 6.8595);
    hist411->Fill(p_mva, 6.8595);  
  }

  input = TFile::Open("/afs/cern.ch/work/x/xuyan/work5/PROD17/DATA/2017/presel/SignalMC1000W_postproc_WGamma17_full_full_jmcorr_May22.root");
  theTree = (TTree*)input->Get("Events");
  // Improt variables for cutting
  theTree->SetBranchAddress("photon_pt", &p_pt);
  theTree->SetBranchAddress("photon_eta", &p_eta);
  theTree->SetBranchAddress("photon_phi", &p_phi);
  theTree->SetBranchAddress("photon_e", &p_e);
  theTree->SetBranchAddress("photon_mvaval", &p_mva);
  theTree->SetBranchAddress("ak8puppijet_pt", &j_pt);
  theTree->SetBranchAddress("ak8puppijet_eta", &j_eta);
  theTree->SetBranchAddress("ak8puppijet_phi", &j_phi);
  theTree->SetBranchAddress("ak8puppijet_e", &j_e);
  theTree->SetBranchAddress("ak8puppijet_masssoftdropcorr", &j_mass);
  theTree->SetBranchAddress("ak8puppijet_tau21", &j_tau21);
  theTree->SetBranchAddress("sys_costhetastar", &s_cos);
  theTree->SetBranchAddress("sys_ptoverm", &s_ptm);
  theTree->SetBranchAddress("m", &s_mass);
  //theTree->SetBranchAddress("xsec_weight", &x_weight);
  
  for (int ievt = 0; ievt<theTree->GetEntries();ievt++) {
    theTree->GetEntry(ievt);
    if(p_pt < 225) continue;
	if(j_pt < 225) continue;
    hist51->Fill(p_pt, 6.8595);
    hist52->Fill(p_eta, 6.8595);
    hist53->Fill(j_pt, 6.8595);
    hist54->Fill(j_eta, 6.8595);
    hist55->Fill(j_e, 6.8595);
    hist56->Fill(j_mass, 5*6.8595);
    hist57->Fill(j_tau21, 6.8595);
    hist58->Fill(s_cos, 6.8595);
    hist59->Fill(s_ptm, 6.8595);
    hist510->Fill(s_mass, 6.8595);
    hist511->Fill(p_mva, 6.8595);  
  }

  input = TFile::Open("/afs/cern.ch/work/x/xuyan/work5/PROD17/DATA/2017/presel/SignalMC2000N_postproc_WGamma17_full_full_jmcorr_May22.root");
  theTree = (TTree*)input->Get("Events");
  // Improt variables for cutting
  theTree->SetBranchAddress("photon_pt", &p_pt);
  theTree->SetBranchAddress("photon_eta", &p_eta);
  theTree->SetBranchAddress("photon_phi", &p_phi);
  theTree->SetBranchAddress("photon_e", &p_e);
  theTree->SetBranchAddress("photon_mvaval", &p_mva);
  theTree->SetBranchAddress("ak8puppijet_pt", &j_pt);
  theTree->SetBranchAddress("ak8puppijet_eta", &j_eta);
  theTree->SetBranchAddress("ak8puppijet_phi", &j_phi);
  theTree->SetBranchAddress("ak8puppijet_e", &j_e);
  theTree->SetBranchAddress("ak8puppijet_masssoftdropcorr", &j_mass);
  theTree->SetBranchAddress("ak8puppijet_tau21", &j_tau21);
  theTree->SetBranchAddress("sys_costhetastar", &s_cos);
  theTree->SetBranchAddress("sys_ptoverm", &s_ptm);
  theTree->SetBranchAddress("m", &s_mass);
  //theTree->SetBranchAddress("xsec_weight", &x_weight);
  
  for (int ievt = 0; ievt<theTree->GetEntries();ievt++) {
    theTree->GetEntry(ievt);
    if(p_pt < 225) continue;
	if(j_pt < 225) continue;
    hist61->Fill(p_pt, 6.8595);
    hist62->Fill(p_eta, 6.8595);
    hist63->Fill(j_pt, 6.8595);
    hist64->Fill(j_eta, 6.8595);
    hist65->Fill(j_e, 6.8595);
    hist66->Fill(j_mass, 5*6.8595);
    hist67->Fill(j_tau21, 6.8595);
    hist68->Fill(s_cos, 6.8595);
    hist69->Fill(s_ptm, 6.8595);
    hist610->Fill(s_mass, 6.8595);
    hist611->Fill(p_mva, 6.8595);  
  }
  
    input = TFile::Open("/afs/cern.ch/work/x/xuyan/work5/PROD17/DATA/2017/presel/SignalMC2000W_postproc_WGamma17_full_full_jmcorr_May22.root");
  theTree = (TTree*)input->Get("Events");
  // Improt variables for cutting
  theTree->SetBranchAddress("photon_pt", &p_pt);
  theTree->SetBranchAddress("photon_eta", &p_eta);
  theTree->SetBranchAddress("photon_phi", &p_phi);
  theTree->SetBranchAddress("photon_e", &p_e);
  theTree->SetBranchAddress("photon_mvaval", &p_mva);
  theTree->SetBranchAddress("ak8puppijet_pt", &j_pt);
  theTree->SetBranchAddress("ak8puppijet_eta", &j_eta);
  theTree->SetBranchAddress("ak8puppijet_phi", &j_phi);
  theTree->SetBranchAddress("ak8puppijet_e", &j_e);
  theTree->SetBranchAddress("ak8puppijet_masssoftdropcorr", &j_mass);
  theTree->SetBranchAddress("ak8puppijet_tau21", &j_tau21);
  theTree->SetBranchAddress("sys_costhetastar", &s_cos);
  theTree->SetBranchAddress("sys_ptoverm", &s_ptm);
  theTree->SetBranchAddress("m", &s_mass);
  //theTree->SetBranchAddress("xsec_weight", &x_weight);
  
  for (int ievt = 0; ievt<theTree->GetEntries();ievt++) {
    theTree->GetEntry(ievt);
    if(p_pt < 225) continue;
	if(j_pt < 225) continue;
    hist71->Fill(p_pt, 6.8595);
    hist72->Fill(p_eta, 6.8595);
    hist73->Fill(j_pt, 6.8595);
    hist74->Fill(j_eta, 6.8595);
    hist75->Fill(j_e, 6.8595);
    hist76->Fill(j_mass, 5*6.8595);
    hist77->Fill(j_tau21, 6.8595);
    hist78->Fill(s_cos, 6.8595);
    hist79->Fill(s_ptm, 6.8595);
    hist710->Fill(s_mass, 6.8595);
    hist711->Fill(p_mva, 6.8595);  
  }
  
  
  // Create stack for bkg MC
  THStack *stack1 = new THStack("stack1","pt_{p}");
  THStack *stack2 = new THStack("stack1","eta_{p}");
  THStack *stack3 = new THStack("stack2","pt_{j}");
  THStack *stack4 = new THStack("stack2","eta_{j}");
  THStack *stack5 = new THStack("stack3","Jet softdrop mass");
  THStack *stack6 = new THStack("stack4","Jet tau21");
  THStack *stack7 = new THStack("stack5","cos(#theta*)");
  THStack *stack8 = new THStack("stack6","pt_{j} / M");
  THStack *stack9 = new THStack("stack7","Invariant mass");
  stack1->Add(hist21); stack1->Add(hist11);
  stack2->Add(hist22); stack2->Add(hist12);
  stack3->Add(hist23); stack3->Add(hist13);
  stack4->Add(hist24); stack4->Add(hist14);
  stack5->Add(hist26); stack5->Add(hist16);
  stack6->Add(hist27); stack6->Add(hist17);
  stack7->Add(hist28); stack7->Add(hist18);
  stack8->Add(hist29); stack8->Add(hist19);
  stack9->Add(hist210); stack9->Add(hist110);


  //=================================================================================
  int color1 = 8;
  int color2 = kAzure+1;
  int color3 = kViolet;
  
  //bkg
  hist11->SetFillColor(color1);
  hist12->SetFillColor(color1);
  hist13->SetFillColor(color1);
  hist14->SetFillColor(color1);
  hist15->SetFillColor(color1);
  hist16->SetFillColor(color1);
  hist17->SetFillColor(color1);
  hist18->SetFillColor(color1);
  hist19->SetFillColor(color1);
  hist110->SetFillColor(color1);
  hist111->SetFillColor(color1);
  hist21->SetFillColor(color2);
  hist22->SetFillColor(color2);
  hist23->SetFillColor(color2);
  hist24->SetFillColor(color2);
  hist25->SetFillColor(color2);
  hist26->SetFillColor(color2);
  hist27->SetFillColor(color2);
  hist28->SetFillColor(color2);
  hist29->SetFillColor(color2);
  hist210->SetFillColor(color2);
  hist211->SetFillColor(color2);
  
  // data
  hist31->SetLineColor(kBlack);
  hist32->SetLineColor(kBlack);
  hist33->SetLineColor(kBlack);
  hist34->SetLineColor(kBlack);
  hist35->SetLineColor(kBlack);
  hist36->SetLineColor(kBlack);
  hist37->SetLineColor(kBlack);
  hist38->SetLineColor(kBlack);
  hist39->SetLineColor(kBlack);
  hist310->SetLineColor(kBlack);
  hist311->SetLineColor(kBlack);
  
  hist31->SetMarkerStyle(20);
  hist32->SetMarkerStyle(20);
  hist33->SetMarkerStyle(20);
  hist34->SetMarkerStyle(20);
  hist35->SetMarkerStyle(20);
  hist36->SetMarkerStyle(20);
  hist37->SetMarkerStyle(20);
  hist38->SetMarkerStyle(20);
  hist39->SetMarkerStyle(20);
  hist310->SetMarkerStyle(20);
  hist311->SetMarkerStyle(20);
  
  hist31->SetMarkerSize(2);
  hist32->SetMarkerSize(2);
  hist33->SetMarkerSize(2);
  hist34->SetMarkerSize(2);
  hist35->SetMarkerSize(2);
  hist36->SetMarkerSize(2);
  hist37->SetMarkerSize(2);
  hist38->SetMarkerSize(2);
  hist39->SetMarkerSize(2);
  hist310->SetMarkerSize(2);
  hist311->SetMarkerSize(2);
  
  hist31->SetMarkerColor(kBlack);
  hist32->SetMarkerColor(kBlack);
  hist33->SetMarkerColor(kBlack);
  hist34->SetMarkerColor(kBlack);
  hist35->SetMarkerColor(kBlack);
  hist36->SetMarkerColor(kBlack);
  hist37->SetMarkerColor(kBlack);
  hist38->SetMarkerColor(kBlack);
  hist39->SetMarkerColor(kBlack);
  hist310->SetMarkerColor(kBlack);
  hist311->SetMarkerColor(kBlack);
  
  hist3a1->SetLineColor(kRed);
  hist3a2->SetLineColor(kRed);
  hist3a3->SetLineColor(kRed);
  hist3a4->SetLineColor(kRed);
  hist3a5->SetLineColor(kRed);
  hist3a6->SetLineColor(kRed);
  hist3a7->SetLineColor(kRed);
  hist3a8->SetLineColor(kRed);
  hist3a9->SetLineColor(kRed);
  hist3a10->SetLineColor(kRed);
  hist3a11->SetLineColor(kRed);
  
  hist3a1->SetMarkerStyle(21);
  hist3a2->SetMarkerStyle(21);
  hist3a3->SetMarkerStyle(21);
  hist3a4->SetMarkerStyle(21);
  hist3a5->SetMarkerStyle(21);
  hist3a6->SetMarkerStyle(21);
  hist3a7->SetMarkerStyle(21);
  hist3a8->SetMarkerStyle(21);
  hist3a9->SetMarkerStyle(21);
  hist3a10->SetMarkerStyle(21);
  hist3a11->SetMarkerStyle(21);
  
  hist3a1->SetMarkerSize(2);
  hist3a2->SetMarkerSize(2);
  hist3a3->SetMarkerSize(2);
  hist3a4->SetMarkerSize(2);
  hist3a5->SetMarkerSize(2);
  hist3a6->SetMarkerSize(2);
  hist3a7->SetMarkerSize(2);
  hist3a8->SetMarkerSize(2);
  hist3a9->SetMarkerSize(2);
  hist3a10->SetMarkerSize(2);
  hist3a11->SetMarkerSize(2);
  
  hist3a1->SetMarkerColor(kRed);
  hist3a2->SetMarkerColor(kRed);
  hist3a3->SetMarkerColor(kRed);
  hist3a4->SetMarkerColor(kRed);
  hist3a5->SetMarkerColor(kRed);
  hist3a6->SetMarkerColor(kRed);
  hist3a7->SetMarkerColor(kRed);
  hist3a8->SetMarkerColor(kRed);
  hist3a9->SetMarkerColor(kRed);
  hist3a10->SetMarkerColor(kRed);
  hist3a11->SetMarkerColor(kRed);
  
  // signal
  hist41->SetLineColor(kPink-9);
  hist42->SetLineColor(kPink-9);
  hist43->SetLineColor(kPink-9);
  hist44->SetLineColor(kPink-9);
  hist45->SetLineColor(kPink-9);
  hist46->SetLineColor(kPink-9);
  hist47->SetLineColor(kPink-9);
  hist48->SetLineColor(kPink-9);
  hist49->SetLineColor(kPink-9);
  hist410->SetLineColor(kPink-9);
  hist411->SetLineColor(kPink-9);
  hist51->SetLineColor(kPink-9);
  hist52->SetLineColor(kPink-9);
  hist53->SetLineColor(kPink-9);
  hist54->SetLineColor(kPink-9);
  hist55->SetLineColor(kPink-9);
  hist56->SetLineColor(kPink-9);
  hist57->SetLineColor(kPink-9);
  hist58->SetLineColor(kPink-9);
  hist59->SetLineColor(kPink-9);
  hist510->SetLineColor(kPink-9);
  hist511->SetLineColor(kPink-9);
  hist61->SetLineColor(kViolet);
  hist62->SetLineColor(kViolet);
  hist63->SetLineColor(kViolet);
  hist64->SetLineColor(kViolet);
  hist65->SetLineColor(kViolet);
  hist66->SetLineColor(kViolet);
  hist67->SetLineColor(kViolet);
  hist68->SetLineColor(kViolet);
  hist69->SetLineColor(kViolet);
  hist610->SetLineColor(kViolet);
  hist611->SetLineColor(kViolet);
  hist71->SetLineColor(kViolet);
  hist72->SetLineColor(kViolet);
  hist73->SetLineColor(kViolet);
  hist74->SetLineColor(kViolet);
  hist75->SetLineColor(kViolet);
  hist76->SetLineColor(kViolet);
  hist77->SetLineColor(kViolet);
  hist78->SetLineColor(kViolet);
  hist79->SetLineColor(kViolet);
  hist710->SetLineColor(kViolet);
  hist711->SetLineColor(kViolet);

  hist41->SetLineStyle(3);
  hist42->SetLineStyle(3);
  hist43->SetLineStyle(3);
  hist44->SetLineStyle(3);
  hist45->SetLineStyle(3);
  hist46->SetLineStyle(3);
  hist47->SetLineStyle(3);
  hist48->SetLineStyle(3);
  hist49->SetLineStyle(3);
  hist410->SetLineStyle(3);
  hist411->SetLineStyle(3);
  hist51->SetLineStyle(2);
  hist52->SetLineStyle(2);
  hist53->SetLineStyle(2);
  hist54->SetLineStyle(2);
  hist55->SetLineStyle(2);
  hist56->SetLineStyle(2);
  hist57->SetLineStyle(2);
  hist58->SetLineStyle(2);
  hist59->SetLineStyle(2);
  hist510->SetLineStyle(2);
  hist511->SetLineStyle(2);
  hist61->SetLineStyle(3);
  hist62->SetLineStyle(3);
  hist63->SetLineStyle(3);
  hist64->SetLineStyle(3);
  hist65->SetLineStyle(3);
  hist66->SetLineStyle(3);
  hist67->SetLineStyle(3);
  hist68->SetLineStyle(3);
  hist69->SetLineStyle(3);
  hist610->SetLineStyle(3);
  hist611->SetLineStyle(3);
  hist71->SetLineStyle(2);
  hist72->SetLineStyle(2);
  hist73->SetLineStyle(2);
  hist74->SetLineStyle(2);
  hist75->SetLineStyle(2);
  hist76->SetLineStyle(2);
  hist77->SetLineStyle(2);
  hist78->SetLineStyle(2);
  hist79->SetLineStyle(2);
  hist710->SetLineStyle(2);
  hist711->SetLineStyle(2);
  
  hist41->SetLineWidth(3);
  hist42->SetLineWidth(3);
  hist43->SetLineWidth(3);
  hist44->SetLineWidth(3);
  hist45->SetLineWidth(3);
  hist46->SetLineWidth(3);
  hist47->SetLineWidth(3);
  hist48->SetLineWidth(3);
  hist49->SetLineWidth(3);
  hist410->SetLineWidth(3);
  hist411->SetLineWidth(3);
  hist51->SetLineWidth(3);
  hist52->SetLineWidth(3);
  hist53->SetLineWidth(3);
  hist54->SetLineWidth(3);
  hist55->SetLineWidth(3);
  hist56->SetLineWidth(3);
  hist57->SetLineWidth(3);
  hist58->SetLineWidth(3);
  hist59->SetLineWidth(3);
  hist510->SetLineWidth(3);
  hist511->SetLineWidth(3);
  hist61->SetLineWidth(3);
  hist62->SetLineWidth(3);
  hist63->SetLineWidth(3);
  hist64->SetLineWidth(3);
  hist65->SetLineWidth(3);
  hist66->SetLineWidth(3);
  hist67->SetLineWidth(3);
  hist68->SetLineWidth(3);
  hist69->SetLineWidth(3);
  hist610->SetLineWidth(3);
  hist611->SetLineWidth(3);
  hist71->SetLineWidth(3);
  hist72->SetLineWidth(3);
  hist73->SetLineWidth(3);
  hist74->SetLineWidth(3);
  hist75->SetLineWidth(3);
  hist76->SetLineWidth(3);
  hist77->SetLineWidth(3);
  hist78->SetLineWidth(3);
  hist79->SetLineWidth(3);
  hist710->SetLineWidth(3);
  hist711->SetLineWidth(3);


  TLegend *legend = new TLegend(0.60,0.75,0.9,0.9);
  legend->SetNColumns(2);
  TAxis *xaxis1 = NULL;
  TAxis *yaxis1 = NULL;
  // Residual plot
  TH1 *data = NULL;
  TH1 *bkg = NULL;
  TH1 *pull = NULL; 
  TAxis *xaxis2 = NULL;
  TAxis *yaxis2 = NULL;
  TAxis *xaxis3 = NULL;
  TAxis *yaxis3 = NULL;

  //===========================================================
  TCanvas *c01 = new TCanvas("c01","",2400,2600);
  c01->cd();
  TPad *p01a = new TPad("p01a","p01a",0,0.32,1,1.0);
  TPad *p01b = new TPad("p01b","p01b",0,0.16,1,0.32);
  TPad *p01c = new TPad("p01c","p01c",0,0,1,0.16);
  p01a->Draw();
  p01b->Draw();
  p01c->Draw();
  p01a->cd();
  p01a->SetBottomMargin(0.12);
  p01a->SetLeftMargin(0.145);
  p01a->SetRightMargin(0.07);
  p01a->SetLogy();
  xaxis1 = hist31->GetXaxis();
  yaxis1 = hist31->GetYaxis();
  xaxis1->SetTitle("p_{T#gamma} (GeV)");
  yaxis1->SetTitle("Entries / 30 GeV");
  xaxis1->SetTitleOffset(1.1);
  yaxis1->SetTitleOffset(1.6);
  yaxis1->SetRangeUser(0.1,1000000);
  hist31->Draw("HIST");
  hist3a1->Draw("SAMEHIST");
  stack1->Draw("SAMEHIST");
  hist41->Draw("SAMEHIST");
  hist51->Draw("SAMEHIST");
  hist61->Draw("SAMEHIST");
  hist71->Draw("SAMEHIST");
  hist31->Draw("E1SAME");
  hist3a1->Draw("E1SAME");
  hist31->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist31,"Data Sideband (Norm)","lep");
  legend->AddEntry(hist41,"M-1000 N");
  legend->AddEntry(hist3a1,"Data Signal Region","lep");
  legend->AddEntry(hist51,"M-1000 W"); 
  legend->AddEntry(hist11,"#gamma + jet","f");
  legend->AddEntry(hist61,"M-2800 N");
  legend->AddEntry(hist21,"QCD","f");
  legend->AddEntry(hist71,"M-2800 W");

  legend->Draw();
  CMS_lumi(p01a,iPeriod,iPos);
  
  p01b->cd();
  p01b->SetTopMargin(0.06);
  p01b->SetBottomMargin(0.4);
  p01b->SetLeftMargin(0.144);
  p01b->SetRightMargin(0.07);
  pull = (TH1*)hist31->Clone();
  bkg = (TH1*)hist11->Clone();
  bkg->Add((TH1*)hist21->Clone());
  pull->Divide(bkg);
  xaxis2 = pull->GetXaxis();
  yaxis2 = pull->GetYaxis();
  xaxis2->SetTitle("p_{T#gamma} (GeV)");
  xaxis2->SetTitleOffset(1.15);
  yaxis2->SetTitle("data/MC");
  yaxis2->SetTitleOffset(0.5);
  yaxis2->SetRangeUser(0,2);
  xaxis2->SetLabelSize(0.15);
  xaxis2->SetLabelOffset(0.04);
  xaxis2->SetTitleSize(0.15);
  yaxis2->SetLabelSize(0.15);
  yaxis2->SetNdivisions(5);
  yaxis2->SetTitleSize(0.15);
  yaxis2->SetTitleOffset(0.4);
  p01b->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  
  p01c->cd();
  p01c->SetTopMargin(0.06);
  p01c->SetBottomMargin(0.4);
  p01c->SetLeftMargin(0.144);
  p01c->SetRightMargin(0.07);
  pull = (TH1*)hist3a1->Clone();
  bkg = (TH1*)hist11->Clone();
  bkg->Add((TH1*)hist21->Clone());
  pull->Divide(bkg);
  xaxis3 = pull->GetXaxis();
  yaxis3 = pull->GetYaxis();
  xaxis3->SetTitle("p_{T#gamma} (GeV)");
  xaxis3->SetTitleOffset(1.15);
  yaxis3->SetTitle("data/MC");
  yaxis3->SetTitleOffset(0.5);
  yaxis3->SetRangeUser(0,2);
  xaxis3->SetLabelSize(0.15);
  xaxis3->SetLabelOffset(0.04);
  xaxis3->SetTitleSize(0.15);
  yaxis3->SetLabelSize(0.15);
  yaxis3->SetNdivisions(5);
  yaxis3->SetTitleSize(0.15);
  yaxis3->SetTitleOffset(0.4);
  p01c->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  c01->Print("p_pt.png");
  c01->Print("p_pt.pdf");
  c01->Print("p_pt.svg");
  c01->Print("p_pt.root");
  //=========================================================
  
  //===========================================================
  TCanvas *c02 = new TCanvas("c02","",2400,2600);
  c02->cd();
  TPad *p02a = new TPad("p02a","p02a",0,0.32,1,1.0);
  TPad *p02b = new TPad("p02b","p02b",0,0.16,1,0.32);
  TPad *p02c = new TPad("p02c","p02c",0,0,1,0.16);
  p02a->Draw();
  p02b->Draw();
  p02c->Draw();
  p02a->cd();
  p02a->SetBottomMargin(0.12);
  p02a->SetLeftMargin(0.145);
  p02a->SetRightMargin(0.07);
  p02a->SetLogy();
  xaxis1 = hist32->GetXaxis();
  yaxis1 = hist32->GetYaxis();
  xaxis1->SetTitle("#eta_{#gamma}");
  yaxis1->SetTitle("Entries / 0.08");
  xaxis1->SetTitleOffset(1.1);
  yaxis1->SetTitleOffset(1.6);
  yaxis1->SetRangeUser(0.1,1000000);
  hist32->Draw("HIST");
  hist3a2->Draw("SAMEHIST");
  stack2->Draw("SAMEHIST");
  hist42->Draw("SAMEHIST");
  hist52->Draw("SAMEHIST");
  hist62->Draw("SAMEHIST");
  hist72->Draw("SAMEHIST");
  hist32->Draw("E1SAME");
  hist3a2->Draw("E1SAME");
  hist32->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist31,"Data Sideband (Norm)","lep");
  legend->AddEntry(hist41,"M-1000 N");
  legend->AddEntry(hist3a1,"Data Signal Region","lep");
  legend->AddEntry(hist51,"M-1000 W"); 
  legend->AddEntry(hist11,"#gamma + jet","f");
  legend->AddEntry(hist61,"M-2800 N");
  legend->AddEntry(hist21,"QCD","f");
  legend->AddEntry(hist71,"M-2800 W");

  legend->Draw();
  CMS_lumi(p02a,iPeriod,iPos);
  
  p02b->cd();
  p02b->SetTopMargin(0.06);
  p02b->SetBottomMargin(0.4);
  p02b->SetLeftMargin(0.144);
  p02b->SetRightMargin(0.07);
  pull = (TH1*)hist32->Clone();
  bkg = (TH1*)hist12->Clone();
  bkg->Add((TH1*)hist22->Clone());
  pull->Divide(bkg);
  xaxis2 = pull->GetXaxis();
  yaxis2 = pull->GetYaxis();
  xaxis2->SetTitle("#eta_{#gamma}");
  xaxis2->SetTitleOffset(1.15);
  yaxis2->SetTitle("data/MC");
  yaxis2->SetTitleOffset(0.5);
  yaxis2->SetRangeUser(0,2);
  xaxis2->SetLabelSize(0.15);
  xaxis2->SetLabelOffset(0.04);
  xaxis2->SetTitleSize(0.15);
  yaxis2->SetLabelSize(0.15);
  yaxis2->SetNdivisions(5);
  yaxis2->SetTitleSize(0.15);
  yaxis2->SetTitleOffset(0.4);
  p02b->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  
  p02c->cd();
  p02c->SetTopMargin(0.06);
  p02c->SetBottomMargin(0.4);
  p02c->SetLeftMargin(0.144);
  p02c->SetRightMargin(0.07);
  pull = (TH1*)hist3a2->Clone();
  bkg = (TH1*)hist12->Clone();
  bkg->Add((TH1*)hist22->Clone());
  pull->Divide(bkg);
  xaxis3 = pull->GetXaxis();
  yaxis3 = pull->GetYaxis();
  xaxis3->SetTitle("#eta_{#gamma}");
  xaxis3->SetTitleOffset(1.15);
  yaxis3->SetTitle("data/MC");
  yaxis3->SetTitleOffset(0.5);
  yaxis3->SetRangeUser(0,2);
  xaxis3->SetLabelSize(0.15);
  xaxis3->SetLabelOffset(0.04);
  xaxis3->SetTitleSize(0.15);
  yaxis3->SetLabelSize(0.15);
  yaxis3->SetNdivisions(5);
  yaxis3->SetTitleSize(0.15);
  yaxis3->SetTitleOffset(0.4);
  p02c->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  c02->Print("p_eta.png");
  c02->Print("p_eta.pdf");
  c02->Print("p_eta.svg");
  c02->Print("p_eta.root");
  //=========================================================
  
    //===========================================================
  TCanvas *c03 = new TCanvas("c03","",2400,2600);
  c03->cd();
  TPad *p03a = new TPad("p03a","p03a",0,0.32,1,1.0);
  TPad *p03b = new TPad("p03b","p03b",0,0.16,1,0.32);
  TPad *p03c = new TPad("p03c","p03c",0,0,1,0.16);
  p03a->Draw();
  p03b->Draw();
  p03c->Draw();
  p03a->cd();
  p03a->SetBottomMargin(0.12);
  p03a->SetLeftMargin(0.145);
  p03a->SetRightMargin(0.07);
  p03a->SetLogy();
  xaxis1 = hist33->GetXaxis();
  yaxis1 = hist33->GetYaxis();
  xaxis1->SetTitle("p_{T j} (GeV)");
  yaxis1->SetTitle("Entries / 30 Gev");
  xaxis1->SetTitleOffset(1.1);
  yaxis1->SetTitleOffset(1.6);
  yaxis1->SetRangeUser(0.1,1000000);
  hist33->Draw("HIST");
  hist3a3->Draw("SAMEHIST");
  stack3->Draw("SAMEHIST");
  hist43->Draw("SAMEHIST");
  hist53->Draw("SAMEHIST");
  hist63->Draw("SAMEHIST");
  hist73->Draw("SAMEHIST");
  hist33->Draw("E1SAME");
  hist3a3->Draw("E1SAME");
  hist33->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist31,"Data Sideband (Norm)","lep");
  legend->AddEntry(hist41,"M-1000 N");
  legend->AddEntry(hist3a1,"Data Signal Region","lep");
  legend->AddEntry(hist51,"M-1000 W"); 
  legend->AddEntry(hist11,"#gamma + jet","f");
  legend->AddEntry(hist61,"M-2800 N");
  legend->AddEntry(hist21,"QCD","f");
  legend->AddEntry(hist71,"M-2800 W");

  legend->Draw();
  CMS_lumi(p03a,iPeriod,iPos);
  
  p03b->cd();
  p03b->SetTopMargin(0.06);
  p03b->SetBottomMargin(0.4);
  p03b->SetLeftMargin(0.144);
  p03b->SetRightMargin(0.07);
  pull = (TH1*)hist33->Clone();
  bkg = (TH1*)hist13->Clone();
  bkg->Add((TH1*)hist23->Clone());
  pull->Divide(bkg);
  xaxis2 = pull->GetXaxis();
  yaxis2 = pull->GetYaxis();
  xaxis2->SetTitle("p_{T j} (GeV)");
  xaxis2->SetTitleOffset(1.15);
  yaxis2->SetTitle("data/MC");
  yaxis2->SetTitleOffset(0.5);
  yaxis2->SetRangeUser(0,2);
  xaxis2->SetLabelSize(0.15);
  xaxis2->SetLabelOffset(0.04);
  xaxis2->SetTitleSize(0.15);
  yaxis2->SetLabelSize(0.15);
  yaxis2->SetNdivisions(5);
  yaxis2->SetTitleSize(0.15);
  yaxis2->SetTitleOffset(0.4);
  p03b->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  
  p03c->cd();
  p03c->SetTopMargin(0.06);
  p03c->SetBottomMargin(0.4);
  p03c->SetLeftMargin(0.144);
  p03c->SetRightMargin(0.07);
  pull = (TH1*)hist3a3->Clone();
  bkg = (TH1*)hist13->Clone();
  bkg->Add((TH1*)hist23->Clone());
  pull->Divide(bkg);
  xaxis3 = pull->GetXaxis();
  yaxis3 = pull->GetYaxis();
  xaxis3->SetTitle("p_{T j} (GeV)");
  xaxis3->SetTitleOffset(1.15);
  yaxis3->SetTitle("data/MC");
  yaxis3->SetTitleOffset(0.5);
  yaxis3->SetRangeUser(0,2);
  xaxis3->SetLabelSize(0.15);
  xaxis3->SetLabelOffset(0.04);
  xaxis3->SetTitleSize(0.15);
  yaxis3->SetLabelSize(0.15);
  yaxis3->SetNdivisions(5);
  yaxis3->SetTitleSize(0.15);
  yaxis3->SetTitleOffset(0.4);
  p03c->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  c03->Print("j_pt.png");
  c03->Print("j_pt.pdf");
  c03->Print("j_pt.svg");
  c03->Print("j_pt.root");
  //=========================================================
  
  //===========================================================
  TCanvas *c04 = new TCanvas("c04","",2400,2600);
  c04->cd();
  TPad *p04a = new TPad("p04a","p04a",0,0.32,1,1.0);
  TPad *p04b = new TPad("p04b","p04b",0,0.16,1,0.32);
  TPad *p04c = new TPad("p04c","p04c",0,0,1,0.16);
  p04a->Draw();
  p04b->Draw();
  p04c->Draw();
  p04a->cd();
  p04a->SetBottomMargin(0.12);
  p04a->SetLeftMargin(0.145);
  p04a->SetRightMargin(0.07);
  p04a->SetLogy();
  xaxis1 = hist34->GetXaxis();
  yaxis1 = hist34->GetYaxis();
  xaxis1->SetTitle("#eta_{j}");
  yaxis1->SetTitle("Entries / 0.08");
  xaxis1->SetTitleOffset(1.1);
  yaxis1->SetTitleOffset(1.6);
  yaxis1->SetRangeUser(0.1,1000000);
  hist34->Draw("PE1");
  hist3a4->Draw("SAMEPE1");
  stack4->Draw("SAMEHIST");
  hist44->Draw("SAMEHIST");
  hist54->Draw("SAMEHIST");
  hist64->Draw("SAMEHIST");
  hist74->Draw("SAMEHIST");
  hist34->Draw("E1SAME");
  hist3a4->Draw("E1SAME");
  hist34->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist34,"Data Sideband (Norm)","lep");
  legend->AddEntry(hist44,"M-1000 N");
  legend->AddEntry(hist3a4,"Data Signal Region","lep");
  legend->AddEntry(hist54,"M-1000 W"); 
  legend->AddEntry(hist14,"#gamma + jet","f");
  legend->AddEntry(hist64,"M-2800 N");
  legend->AddEntry(hist24,"QCD","f");
  legend->AddEntry(hist74,"M-2800 W");
  legend->Draw();
  CMS_lumi(p04a,iPeriod,iPos);
  
  p04b->cd();
  p04b->SetTopMargin(0.06);
  p04b->SetBottomMargin(0.4);
  p04b->SetLeftMargin(0.144);
  p04b->SetRightMargin(0.07);
  pull = (TH1*)hist34->Clone();
  bkg = (TH1*)hist14->Clone();
  bkg->Add((TH1*)hist24->Clone());
  pull->Divide(bkg);
  xaxis2 = pull->GetXaxis();
  yaxis2 = pull->GetYaxis();
  xaxis2->SetTitle("#eta_{j}");
  xaxis2->SetTitleOffset(1.15);
  yaxis2->SetTitle("data/MC");
  yaxis2->SetTitleOffset(0.5);
  yaxis2->SetRangeUser(0,2);
  xaxis2->SetLabelSize(0.15);
  xaxis2->SetLabelOffset(0.04);
  xaxis2->SetTitleSize(0.15);
  yaxis2->SetLabelSize(0.15);
  yaxis2->SetNdivisions(5);
  yaxis2->SetTitleSize(0.15);
  yaxis2->SetTitleOffset(0.4);
  p04b->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  
  p04c->cd();
  p04c->SetTopMargin(0.06);
  p04c->SetBottomMargin(0.4);
  p04c->SetLeftMargin(0.144);
  p04c->SetRightMargin(0.07);
  pull = (TH1*)hist3a4->Clone();
  bkg = (TH1*)hist14->Clone();
  bkg->Add((TH1*)hist24->Clone());
  pull->Divide(bkg);
  xaxis3 = pull->GetXaxis();
  yaxis3 = pull->GetYaxis();
  xaxis3->SetTitle("#eta_{j}");
  xaxis3->SetTitleOffset(1.15);
  yaxis3->SetTitle("data/MC");
  yaxis3->SetTitleOffset(0.5);
  yaxis3->SetRangeUser(0,2);
  xaxis3->SetLabelSize(0.15);
  xaxis3->SetLabelOffset(0.04);
  xaxis3->SetTitleSize(0.15);
  yaxis3->SetLabelSize(0.15);
  yaxis3->SetNdivisions(5);
  yaxis3->SetTitleSize(0.15);
  yaxis3->SetTitleOffset(0.4);
  p04c->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  c04->Print("j_eta.png");
  c04->Print("j_eta.pdf");
  c04->Print("j_eta.svg");
  c04->Print("j_eta.root");
  //==========================================================
  
  
    //===========================================================
  TCanvas *c05 = new TCanvas("c05","",2400,2600);
  c05->cd();
  TPad *p05a = new TPad("p05a","p05a",0,0.32,1,1.0);
  TPad *p05b = new TPad("p05b","p05b",0,0.16,1,0.32);
  TPad *p05c = new TPad("p05c","p05c",0,0,1,0.16);
  p05a->Draw();
  p05b->Draw();
  p05c->Draw();
  p05a->cd();
  p05a->SetBottomMargin(0.12);
  p05a->SetLeftMargin(0.145);
  p05a->SetRightMargin(0.07);
  xaxis1 = hist36->GetXaxis();
  yaxis1 = hist36->GetYaxis();
  xaxis1->SetTitle("m_{j} (GeV)");
  yaxis1->SetTitle("Entries / 1 GeV");
  xaxis1->SetTitleOffset(1.1);
  yaxis1->SetTitleOffset(1.6);
  yaxis1->SetRangeUser(0,20000);
  hist36->Draw("PE1");
  hist3a6->Draw("SAMEPE1");
  stack5->Draw("SAMEHIST");
  hist46->Draw("SAMEHIST");
  hist56->Draw("SAMEHIST");
  hist66->Draw("SAMEHIST");
  hist76->Draw("SAMEHIST");
  hist36->Draw("E1SAME");
  hist3a6->Draw("E1SAME");
  hist36->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist36,"Data Sideband","lep");
  legend->AddEntry(hist46,"M-1000 N");
  legend->AddEntry(hist3a6,"Data Signal Region","lep");
  legend->AddEntry(hist56,"M-1000 W"); 
  legend->AddEntry(hist16,"#gamma + jet","f");
  legend->AddEntry(hist66,"M-2800 N");
  legend->AddEntry(hist26,"QCD","f");
  legend->AddEntry(hist76,"M-2800 W");
  legend->Draw();
  CMS_lumi(p05a,iPeriod,iPos);
  
  p05b->cd();
  p05b->SetTopMargin(0.06);
  p05b->SetBottomMargin(0.4);
  p05b->SetLeftMargin(0.144);
  p05b->SetRightMargin(0.07);
  pull = (TH1*)hist36->Clone();
  bkg = (TH1*)hist16->Clone();
  bkg->Add((TH1*)hist26->Clone());
  pull->Divide(bkg);
  xaxis2 = pull->GetXaxis();
  yaxis2 = pull->GetYaxis();
  xaxis2->SetTitle("m_{j} (GeV)");
  xaxis2->SetTitleOffset(1.15);
  yaxis2->SetTitle("data/MC");
  yaxis2->SetTitleOffset(0.5);
  yaxis2->SetRangeUser(0,2);
  xaxis2->SetLabelSize(0.15);
  xaxis2->SetLabelOffset(0.04);
  xaxis2->SetTitleSize(0.15);
  yaxis2->SetLabelSize(0.15);
  yaxis2->SetNdivisions(5);
  yaxis2->SetTitleSize(0.15);
  yaxis2->SetTitleOffset(0.4);
  p05b->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  
  p05c->cd();
  p05c->SetTopMargin(0.06);
  p05c->SetBottomMargin(0.4);
  p05c->SetLeftMargin(0.144);
  p05c->SetRightMargin(0.07);
  pull = (TH1*)hist3a6->Clone();
  bkg = (TH1*)hist16->Clone();
  bkg->Add((TH1*)hist26->Clone());
  pull->Divide(bkg);
  xaxis3 = pull->GetXaxis();
  yaxis3 = pull->GetYaxis();
  xaxis3->SetTitle("m_{j} (GeV)");
  xaxis3->SetTitleOffset(1.15);
  yaxis3->SetTitle("data/MC");
  yaxis3->SetTitleOffset(0.5);
  yaxis3->SetRangeUser(0,2);
  xaxis3->SetLabelSize(0.15);
  xaxis3->SetLabelOffset(0.04);
  xaxis3->SetTitleSize(0.15);
  yaxis3->SetLabelSize(0.15);
  yaxis3->SetNdivisions(5);
  yaxis3->SetTitleSize(0.15);
  yaxis3->SetTitleOffset(0.4);
  p05c->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  c05->Print("j_m.png");
  c05->Print("j_m.pdf");
  c05->Print("j_m.svg");
  c05->Print("j_m.root");
  //==========================================================
  
  //===========================================================
  TCanvas *c06 = new TCanvas("c06","",2400,2600);
  c06->cd();
  TPad *p06a = new TPad("p06a","p06a",0,0.32,1,1.0);
  TPad *p06b = new TPad("p06b","p06b",0,0.16,1,0.32);
  TPad *p06c = new TPad("p06c","p06c",0,0,1,0.16);
  p06a->Draw();
  p06b->Draw();
  p06c->Draw();
  p06a->cd();
  p06a->SetBottomMargin(0.12);
  p06a->SetLeftMargin(0.145);
  p06a->SetRightMargin(0.07);
  //p06a->SetLogy();
  xaxis1 = hist37->GetXaxis();
  yaxis1 = hist37->GetYaxis();
  xaxis1->SetTitle("#tau_{21}");
  yaxis1->SetTitle("Entries / 0.02");
  xaxis1->SetTitleOffset(1.1);
  yaxis1->SetTitleOffset(1.6);
  yaxis1->SetRangeUser(0,16000);
  hist37->Draw("PE1");
  hist3a7->Draw("SAMEPE1");
  stack6->Draw("SAMEHIST");
  hist47->Draw("SAMEHIST");
  hist57->Draw("SAMEHIST");
  hist67->Draw("SAMEHIST");
  hist77->Draw("SAMEHIST");
  hist37->Draw("E1SAME");
  hist3a7->Draw("E1SAME");
  hist37->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist37,"Data Sideband (Norm)","lep");
  legend->AddEntry(hist47,"M-1000 N");
  legend->AddEntry(hist3a7,"Data Signal Region","lep");
  legend->AddEntry(hist57,"M-1000 W"); 
  legend->AddEntry(hist17,"#gamma + jet","f");
  legend->AddEntry(hist67,"M-2800 N");
  legend->AddEntry(hist27,"QCD","f");
  legend->AddEntry(hist77,"M-2800 W");
  legend->Draw();
  CMS_lumi(p06a,iPeriod,iPos);
  
  p06b->cd();
  p06b->SetTopMargin(0.06);
  p06b->SetBottomMargin(0.4);
  p06b->SetLeftMargin(0.144);
  p06b->SetRightMargin(0.07);
  pull = (TH1*)hist37->Clone();
  bkg = (TH1*)hist17->Clone();
  bkg->Add((TH1*)hist27->Clone());
  pull->Divide(bkg);
  xaxis2 = pull->GetXaxis();
  yaxis2 = pull->GetYaxis();
  xaxis2->SetTitle("#tau_{21}");
  xaxis2->SetTitleOffset(1.15);
  yaxis2->SetTitle("data/MC");
  yaxis2->SetTitleOffset(0.5);
  yaxis2->SetRangeUser(0,2);
  xaxis2->SetLabelSize(0.15);
  xaxis2->SetLabelOffset(0.04);
  xaxis2->SetTitleSize(0.15);
  yaxis2->SetLabelSize(0.15);
  yaxis2->SetNdivisions(5);
  yaxis2->SetTitleSize(0.15);
  yaxis2->SetTitleOffset(0.4);
  p06b->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  
  p06c->cd();
  p06c->SetTopMargin(0.06);
  p06c->SetBottomMargin(0.4);
  p06c->SetLeftMargin(0.144);
  p06c->SetRightMargin(0.07);
  pull = (TH1*)hist3a7->Clone();
  bkg = (TH1*)hist17->Clone();
  bkg->Add((TH1*)hist27->Clone());
  pull->Divide(bkg);
  xaxis3 = pull->GetXaxis();
  yaxis3 = pull->GetYaxis();
  xaxis3->SetTitle("#tau_{21}");
  xaxis3->SetTitleOffset(1.15);
  yaxis3->SetTitle("data/MC");
  yaxis3->SetRangeUser(0,2);
  xaxis3->SetLabelSize(0.15);
  xaxis3->SetLabelOffset(0.04);
  xaxis3->SetTitleSize(0.15);
  yaxis3->SetLabelSize(0.15);
  yaxis3->SetNdivisions(5);
  yaxis3->SetTitleSize(0.15);
  yaxis3->SetTitleOffset(0.4);
  p06c->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  c06->Print("j_tau21.png");
  c06->Print("j_tau21.pdf");
  c06->Print("j_tau21.svg");
  c06->Print("j_tau21.root");
  //==========================================================
  
  //===========================================================
  TCanvas *c07 = new TCanvas("c07","",2400,2600);
  c07->cd();
  TPad *p07a = new TPad("p07a","p07a",0,0.32,1,1.0);
  TPad *p07b = new TPad("p07b","p07b",0,0.16,1,0.32);
  TPad *p07c = new TPad("p07c","p07c",0,0,1,0.16);
  p07a->Draw();
  p07b->Draw();
  p07c->Draw();
  p07a->cd();
  p07a->SetBottomMargin(0.12);
  p07a->SetLeftMargin(0.145);
  p07a->SetRightMargin(0.07);
  p07a->SetLogy();
  xaxis1 = hist38->GetXaxis();
  yaxis1 = hist38->GetYaxis();
  xaxis1->SetTitle("cos(#theta*)");
  yaxis1->SetTitle("Entries / 0.02");
  xaxis1->SetTitleOffset(1.1);
  yaxis1->SetTitleOffset(1.6);
  yaxis1->SetRangeUser(0.1,1000000);
  hist38->Draw("PE1");
  hist3a8->Draw("SAMEPE1");
  stack7->Draw("SAMEHIST");
  hist48->Draw("SAMEHIST");
  hist58->Draw("SAMEHIST");
  hist68->Draw("SAMEHIST");
  hist78->Draw("SAMEHIST");
  hist38->Draw("E1SAME");
  hist3a8->Draw("E1SAME");
  hist38->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist38,"Data Sideband (Norm)","lep");
  legend->AddEntry(hist48,"M-1000 N");
  legend->AddEntry(hist3a8,"Data Signal Region","lep");
  legend->AddEntry(hist58,"M-1000 W"); 
  legend->AddEntry(hist18,"#gamma + jet","f");
  legend->AddEntry(hist68,"M-2800 N");
  legend->AddEntry(hist28,"QCD","f");
  legend->AddEntry(hist78,"M-2800 W");
  legend->Draw();
  CMS_lumi(p07a,iPeriod,iPos);
  
  p07b->cd();
  p07b->SetTopMargin(0.06);
  p07b->SetBottomMargin(0.4);
  p07b->SetLeftMargin(0.144);
  p07b->SetRightMargin(0.07);
  pull = (TH1*)hist38->Clone();
  bkg = (TH1*)hist18->Clone();
  bkg->Add((TH1*)hist28->Clone());
  pull->Divide(bkg);
  xaxis2 = pull->GetXaxis();
  yaxis2 = pull->GetYaxis();
  xaxis2->SetTitle("cos(#theta*)");
  xaxis2->SetTitleOffset(1.15);
  yaxis2->SetTitle("data/MC");
  yaxis2->SetTitleOffset(0.5);
  yaxis2->SetRangeUser(0,2);
  xaxis2->SetLabelSize(0.15);
  xaxis2->SetLabelOffset(0.04);
  xaxis2->SetTitleSize(0.15);
  yaxis2->SetLabelSize(0.15);
  yaxis2->SetNdivisions(5);
  yaxis2->SetTitleSize(0.15);
  yaxis2->SetTitleOffset(0.4);
  p07b->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  
  p07c->cd();
  p07c->SetTopMargin(0.06);
  p07c->SetBottomMargin(0.4);
  p07c->SetLeftMargin(0.144);
  p07c->SetRightMargin(0.07);
  pull = (TH1*)hist3a8->Clone();
  bkg = (TH1*)hist18->Clone();
  bkg->Add((TH1*)hist28->Clone());
  pull->Divide(bkg);
  xaxis3 = pull->GetXaxis();
  yaxis3 = pull->GetYaxis();
  xaxis3->SetTitle("cos(#theta*)");
  xaxis3->SetTitleOffset(1.15);
  yaxis3->SetTitle("data/MC");
  yaxis3->SetTitleOffset(0.5);
  yaxis3->SetRangeUser(0,2);
  xaxis3->SetLabelSize(0.15);
  xaxis3->SetLabelOffset(0.04);
  xaxis3->SetTitleSize(0.15);
  yaxis3->SetLabelSize(0.15);
  yaxis3->SetNdivisions(5);
  yaxis3->SetTitleSize(0.15);
  yaxis3->SetTitleOffset(0.4);
  p07c->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  c07->Print("s_cos.png");
  c07->Print("s_cos.pdf");
  c07->Print("s_cos.svg");
  c07->Print("s_cos.root");
  //==========================================================
  
  //===========================================================
  TCanvas *c08 = new TCanvas("c08","",2400,2600);
  c08->cd();
  TPad *p08a = new TPad("p08a","p08a",0,0.32,1,1.0);
  TPad *p08b = new TPad("p08b","p08b",0,0.16,1,0.32);
  TPad *p08c = new TPad("p08c","p08c",0,0,1,0.16);
  p08a->Draw();
  p08b->Draw();
  p08c->Draw();
  p08a->cd();
  p08a->SetBottomMargin(0.12);
  p08a->SetLeftMargin(0.145);
  p08a->SetRightMargin(0.07);
  p08a->SetLogy();
  xaxis1 = hist39->GetXaxis();
  yaxis1 = hist39->GetYaxis();
  xaxis1->SetTitle("pT_{#gamma} / M_{j#gamma}");
  yaxis1->SetTitle("Entries / 0.04");
  xaxis1->SetTitleOffset(1.1);
  yaxis1->SetTitleOffset(1.6);
  yaxis1->SetRangeUser(0.1,1000000);
  hist39->Draw("PE1");
  hist3a9->Draw("SAMEPE1");
  stack8->Draw("SAMEHIST");
  hist49->Draw("SAMEHIST");
  hist59->Draw("SAMEHIST");
  hist69->Draw("SAMEHIST");
  hist79->Draw("SAMEHIST");
  hist39->Draw("E1SAME");
  hist3a9->Draw("E1SAME");
  hist39->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist39,"Data Sideband (Norm)","lep");
  legend->AddEntry(hist49,"M-1000 N");
  legend->AddEntry(hist3a9,"Data Signal Region","lep");
  legend->AddEntry(hist59,"M-1000 W"); 
  legend->AddEntry(hist19,"#gamma + jet","f");
  legend->AddEntry(hist69,"M-2800 N");
  legend->AddEntry(hist29,"QCD","f");
  legend->AddEntry(hist79,"M-2800 W");
  legend->Draw();
  CMS_lumi(p08a,iPeriod,iPos);
  
  p08b->cd();
  p06b->SetTopMargin(0.06);
  p08b->SetBottomMargin(0.4);
  p08b->SetLeftMargin(0.144);
  p08b->SetRightMargin(0.07);
  pull = (TH1*)hist39->Clone();
  bkg = (TH1*)hist19->Clone();
  bkg->Add((TH1*)hist29->Clone());
  pull->Divide(bkg);
  xaxis2 = pull->GetXaxis();
  yaxis2 = pull->GetYaxis();
  xaxis2->SetTitle("pT_{#gamma} / M_{j#gamma}");
  xaxis2->SetTitleOffset(1.15);
  yaxis2->SetTitle("data/MC");
  yaxis2->SetTitleOffset(0.5);
  yaxis2->SetRangeUser(0,2);
  xaxis2->SetLabelSize(0.15);
  xaxis2->SetLabelOffset(0.04);
  xaxis2->SetTitleSize(0.15);
  yaxis2->SetLabelSize(0.15);
  yaxis2->SetNdivisions(5);
  yaxis2->SetTitleSize(0.15);
  yaxis2->SetTitleOffset(0.4);
  p08b->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  
  p08c->cd();
  p08c->SetTopMargin(0.06);
  p08c->SetBottomMargin(0.4);
  p08c->SetLeftMargin(0.144);
  p08c->SetRightMargin(0.07);
  pull = (TH1*)hist3a9->Clone();
  bkg = (TH1*)hist19->Clone();
  bkg->Add((TH1*)hist29->Clone());
  pull->Divide(bkg);
  xaxis3 = pull->GetXaxis();
  yaxis3 = pull->GetYaxis();
  xaxis3->SetTitle("pT_{#gamma} / M_{j#gamma}");
  xaxis3->SetTitleOffset(1.15);
  yaxis3->SetTitle("data/MC");
  yaxis3->SetTitleOffset(0.5);
  yaxis3->SetRangeUser(0,2);
  xaxis3->SetLabelSize(0.15);
  xaxis3->SetLabelOffset(0.04);
  xaxis3->SetTitleSize(0.15);
  yaxis3->SetLabelSize(0.15);
  yaxis3->SetNdivisions(5);
  yaxis3->SetTitleSize(0.15);
  yaxis3->SetTitleOffset(0.4);
  p08c->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  c08->Print("s_ptm.png");
  c08->Print("s_ptm.pdf");
  c08->Print("s_ptm.svg");
  c08->Print("s_ptm.root");
  //==========================================================
  
  legend = new TLegend(0.57,0.75,0.9,0.9);
  legend->SetNColumns(2);
  //===========================================================
  TCanvas *c09 = new TCanvas("c09","",2400,2600);
  c09->cd();
  TPad *p09a = new TPad("p09a","p09a",0,0.20,1,1.0);
  TPad *p09b = new TPad("p09b","p09b",0,0.0,1,0.20);
  TPad *p09c = new TPad("p09c","p09c",0,0,1,0.16);
  p09a->Draw();
  p09b->Draw();
  //p09c->Draw();
  p09a->cd();
  p09a->SetBottomMargin(0.12);
  p09a->SetLeftMargin(0.145);
  p09a->SetRightMargin(0.07);
  p09a->SetLogy();
  xaxis1 = hist310->GetXaxis();
  yaxis1 = hist310->GetYaxis();
  xaxis1->SetTitle("M_{j#gamma} (GeV)");
  yaxis1->SetTitle("Entries / 40 GeV");
  xaxis1->SetTitleOffset(1.1);
  yaxis1->SetTitleOffset(1.6);
  xaxis1->SetTitleSize(0.03);
  xaxis1->SetLabelSize(0.03);
  yaxis1->SetTitleSize(0.03);
  yaxis1->SetLabelSize(0.03);
  yaxis1->SetRangeUser(0.1,1000000);
  hist310->Draw("PE1");
  //hist3a10->Draw("SAMEPE1");
  stack9->Draw("SAMEHIST");
  hist410->Draw("SAMEHIST");
  hist510->Draw("SAMEHIST");
  hist610->Draw("SAMEHIST");
  hist710->Draw("SAMEHIST");
  hist310->Draw("E1SAME");
  //hist3a10->Draw("E1SAME");
  hist310->Draw("AXISSAME");
  legend->Clear();
  legend->AddEntry(hist310,"Data Sideband (Norm)","lep");
  legend->AddEntry(hist410,"M-1000 N");
  legend->AddEntry(hist110,"#gamma + jet","f");
  legend->AddEntry(hist510,"M-1000 W");
  legend->AddEntry(hist210,"QCD","f");
  legend->AddEntry(hist610,"M-2800 N");
  legend->AddEntry(hist710,"M-2800 W");
  
  legend->Draw();
  CMS_lumi(p09a,iPeriod,iPos);
  
  p09b->cd();
  p06b->SetTopMargin(0.06);
  p09b->SetBottomMargin(0.4);
  p09b->SetLeftMargin(0.144);
  p09b->SetRightMargin(0.07);
  pull = (TH1*)hist310->Clone();
  bkg = (TH1*)hist110->Clone();
  bkg->Add((TH1*)hist210->Clone());
  pull->Divide(bkg);
  xaxis2 = pull->GetXaxis();
  yaxis2 = pull->GetYaxis();
  xaxis2->SetTitle("M_{j#gamma} (GeV)");
  xaxis2->SetTitleOffset(1.15);
  yaxis2->SetTitle("data/MC");
  yaxis2->SetTitleOffset(0.5);
  yaxis2->SetRangeUser(0,2);
  xaxis2->SetLabelSize(0.12);
  xaxis2->SetLabelOffset(0.04);
  xaxis2->SetTitleSize(0.12);
  yaxis2->SetLabelSize(0.12);
  yaxis2->SetNdivisions(5);
  yaxis2->SetTitleSize(0.12);
  p09b->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  
  /*
  p09c->cd();
  p09c->SetTopMargin(0.06);
  p09c->SetBottomMargin(0.4);
  p09c->SetLeftMargin(0.144);
  p09c->SetRightMargin(0.07);
  pull = (TH1*)hist3a10->Clone();
  bkg = (TH1*)hist110->Clone();
  bkg->Add((TH1*)hist210->Clone());
  pull->Divide(bkg);
  xaxis3 = pull->GetXaxis();
  yaxis3 = pull->GetYaxis();
  xaxis3->SetTitle("M_{j#gamma} (GeV)");
  xaxis3->SetTitleOffset(1.15);
  yaxis3->SetTitle("data/MC");
  yaxis3->SetTitleOffset(0.5);
  yaxis3->SetRangeUser(0,2);
  xaxis3->SetLabelSize(0.15);
  xaxis3->SetTitleSize(0.15);
  yaxis3->SetLabelSize(0.15);
  yaxis3->SetNdivisions(5);
  yaxis3->SetTitleSize(0.15);
  yaxis3->SetTitleOffset(0.4);
  p09c->SetGrid();
  //pull->SetFillColor(kViolet);
  //pull->SetLineColor(kViolet);
  //pull->SetFillColorAlpha(kViolet, 0.35);
  pull->Draw("PE1");
  //pull->Draw("BAR HIST");
  */
  
  c09->Print("s_M.png");
  c09->Print("s_M.pdf");
  c09->Print("s_M.svg");
  c09->Print("s_M.root");
  //==========================================================
  
  cout<<SB<<endl;
  cout<<WB<<endl;
}